const FIELD_STORAGE_KEY = 'field-ops-dashboard-data';
const TEST_STORAGE_KEY = 'lab-wip-test-definitions';
const state = { methods:[], testTypes:[], filters:{ search:'', section:'all', status:'active' }, editingId:'', saving:false };

function esc(value){ return String(value ?? '').replace(/[&<>"']/g,(ch)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])); }
function normalizeKey(value){ return String(value || '').trim().toUpperCase().replace(/\s+/g,'_').replace(/[^A-Z0-9_-]/g,''); }
function uid(prefix){ return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; }
function isRemote(){ return window.appAuth?.getMode?.() === 'remote'; }
function testTypeFor(method){ return state.testTypes.find((row)=>row.id === method.testTypeId) || null; }
function normalizeTestType(row,index=0,remote=false){ return { id:String(row?.id || row?.key || uid('testtype')), testCode:normalizeKey(remote?row?.test_code:(row?.testCode||row?.key)), displayLabel:String((remote?row?.display_label:(row?.displayLabel||row?.label))||''), shortLabel:String((remote?row?.short_label:(row?.shortLabel))||''), minutes:Number((remote?row?.minutes:row?.minutes)||0), countMode:String((remote?row?.count_mode:row?.countMode)||'perSample'), matrixType:String((remote?row?.matrix_type:row?.matrixType)||''), groupKey:String((remote?row?.group_key:row?.groupKey)||''), groupRank:Number((remote?row?.group_rank:row?.groupRank)||0), aliases:Array.isArray(remote?row?.aliases:row?.aliases)?(remote?row.aliases:row.aliases):[], sortOrder:Number((remote?row?.sort_order:row?.sortOrder)??index), labWipEnabled:(remote?row?.lab_wip_enabled:row?.labWipEnabled)!==false, isActive:(remote?row?.is_active:row?.isActive)!==false }; }
function normalizeMethod(row,index=0,remote=false){ return { id:String(row?.id||uid('method')), testTypeId:String((remote?row?.test_type_id:row?.testTypeId)||''), itemKey:String((remote?row?.item_key:row?.itemKey)||''), priceSection:String((remote?row?.price_section:row?.priceSection)||''), category:String((remote?row?.category:row?.category)||''), method:String((remote?row?.method:row?.method)||''), description:String((remote?row?.description:row?.description)||''), unitName:String((remote?row?.unit_name:row?.unitName)||'Per Sample'), sortOrder:Number((remote?row?.sort_order:row?.sortOrder)??index*10), isActive:(remote?row?.is_active:row?.isActive)!==false, notes:String((remote?row?.notes:row?.notes)||'') }; }
function localStorageAdapter(){ return window.storage || { get:async(key)=>({value:localStorage.getItem(key)}), set:async(key,value)=>localStorage.setItem(key,value) }; }

async function loadData(){
  if(isRemote()){
    const [testRows,methodRows] = await Promise.all([window.appAuth.requestJson('/rest/v1/lab_test_types?select=*&order=sort_order.asc,test_code.asc'),window.appAuth.requestJson('/rest/v1/billing_price_items?select=*&order=sort_order.asc,method.asc,description.asc')]);
    state.testTypes=(testRows||[]).map((row,index)=>normalizeTestType(row,index,true));
    state.methods=(methodRows||[]).map((row,index)=>normalizeMethod(row,index,true));
  } else {
    const storage=localStorageAdapter();
    const [fieldResult,testResult]=await Promise.all([storage.get(FIELD_STORAGE_KEY),storage.get(TEST_STORAGE_KEY)]);
    const field=fieldResult?.value?JSON.parse(fieldResult.value):{};
    const tests=testResult?.value?JSON.parse(testResult.value):[];
    state.testTypes=(Array.isArray(tests)&&tests.length?tests:(Array.isArray(field.testTypes)?field.testTypes:[])).map((row,index)=>normalizeTestType(row,index,false));
    state.methods=(Array.isArray(field.priceItems)?field.priceItems:[]).map((row,index)=>normalizeMethod(row,index,false));
  }
  render();
}
function setMethodFilter(key,value){ state.filters[key]=String(value||''); render(); }
function visibleMethods(){ const q=state.filters.search.trim().toLowerCase(); return state.methods.filter((method)=>{ const type=testTypeFor(method); if(state.filters.status==='active'&&method.isActive===false)return false; if(state.filters.status==='archived'&&method.isActive!==false)return false; if(state.filters.status==='unmapped'&&method.testTypeId)return false; if(state.filters.section!=='all'&&method.priceSection!==state.filters.section)return false; return !q||[type?.testCode,method.method,method.description,method.priceSection].some((v)=>String(v||'').toLowerCase().includes(q)); }); }
function render(){
  document.getElementById('stat-total').textContent=state.methods.length;
  document.getElementById('stat-mapped').textContent=state.methods.filter((m)=>m.testTypeId).length;
  document.getElementById('stat-unmapped').textContent=state.methods.filter((m)=>!m.testTypeId).length;
  document.getElementById('stat-archived').textContent=state.methods.filter((m)=>m.isActive===false).length;
  const rows=visibleMethods();
  document.getElementById('methods-tbody').innerHTML=rows.length?rows.map((method)=>{ const type=testTypeFor(method); return `<tr><td>${type?`<div class="record-title">${esc(type.testCode)}</div><div class="record-sub">${esc(type.displayLabel||type.testCode)}</div>`:'<span class="mapping-warning">Needs Test Type</span>'}</td><td>${esc(method.method||'—')}</td><td>${esc(method.description)}</td><td>${esc(method.priceSection)}</td><td>${esc(type?.matrixType||'—')}</td><td>${esc(method.unitName)}</td><td>${type?(type.labWipEnabled?'Yes':'Hidden'):'—'}</td><td><span class="status-pill ${method.isActive===false?'archived':method.testTypeId?'ok':'warn'}">${method.isActive===false?'Archived':method.testTypeId?'Mapped':'Needs mapping'}</span></td><td><div class="method-actions"><button class="sec-btn small" onclick="openMethodModal('${esc(method.id)}')">Edit</button><button class="sec-btn small" onclick="toggleMethodArchive('${esc(method.id)}')">${method.isActive===false?'Restore':'Archive'}</button></div></td></tr>`; }).join(''):'<tr><td colspan="9"><div class="empty-state">No methods match these filters.</div></td></tr>';
  document.getElementById('last-update').textContent=`${rows.length} shown | ${isRemote()?'Remote':'Local'} | ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`;
}
function buildTestTypeOptions(selected=''){ return ['<option value="">Select Test Code...</option>',...state.testTypes.filter((t)=>t.isActive!==false).map((t)=>`<option value="${esc(t.id)}" ${t.id===selected?'selected':''}>${esc(t.testCode)} | ${esc(t.displayLabel||t.testCode)}</option>`)].join(''); }
function openMethodModal(id=''){
  const method=state.methods.find((row)=>row.id===id)||null; state.editingId=method?.id||'';
  document.getElementById('method-modal-title').textContent=method?'Edit Method':'Add Method';
  document.getElementById('method-test-type-mode').value='existing'; document.getElementById('method-test-type-id').innerHTML=buildTestTypeOptions(method?.testTypeId||'');
  document.getElementById('method-standard').value=method?.method||''; document.getElementById('method-description').value=method?.description||''; document.getElementById('method-price-section').value=method?.priceSection||'Liquid Samples'; document.getElementById('method-category').value=method?.category||'Liquid'; document.getElementById('method-unit').value=method?.unitName||'Per Sample'; document.getElementById('method-sort-order').value=String(method?.sortOrder??((state.methods.length+1)*10)); document.getElementById('method-notes').value=method?.notes||'';
  ['new-test-code','new-display-label','new-short-label','new-group-key','new-aliases'].forEach((id)=>document.getElementById(id).value=''); document.getElementById('new-minutes').value='15'; document.getElementById('new-count-mode').value='perSample'; document.getElementById('new-matrix-type').value=''; document.getElementById('new-group-rank').value='0'; document.getElementById('new-lab-wip-enabled').checked=true;
  changeTestTypeMode('existing'); document.getElementById('method-test-type-mode').disabled=false; document.getElementById('method-modal-overlay').classList.add('open');
}
function closeMethodModal(){ state.editingId=''; document.getElementById('method-modal-overlay').classList.remove('open'); }
function changeTestTypeMode(mode){ const isNew=mode==='new'; document.getElementById('new-test-type-fields').classList.toggle('open',isNew); document.getElementById('existing-test-type-group').style.display=isNew?'none':''; }
function readMethodForm(){ const testTypeMode=document.getElementById('method-test-type-mode').value; const method={ testTypeId:testTypeMode==='existing'?document.getElementById('method-test-type-id').value:'', method:document.getElementById('method-standard').value.trim(), description:document.getElementById('method-description').value.trim(), priceSection:document.getElementById('method-price-section').value, category:document.getElementById('method-category').value, unitName:document.getElementById('method-unit').value.trim(), sortOrder:Number(document.getElementById('method-sort-order').value||0), notes:document.getElementById('method-notes').value.trim(), isActive:true }; const testType=testTypeMode==='new'?{ testCode:normalizeKey(document.getElementById('new-test-code').value), displayLabel:document.getElementById('new-display-label').value.trim(), shortLabel:document.getElementById('new-short-label').value.trim(), minutes:Number(document.getElementById('new-minutes').value||0), countMode:document.getElementById('new-count-mode').value, matrixType:document.getElementById('new-matrix-type').value, groupKey:normalizeKey(document.getElementById('new-group-key').value), groupRank:Number(document.getElementById('new-group-rank').value||0), aliases:document.getElementById('new-aliases').value.split(',').map((v)=>v.trim()).filter(Boolean), labWipEnabled:document.getElementById('new-lab-wip-enabled').checked }:null; return {method,testType}; }
function validateForm(data){ if(!data.method.description)return 'Description is required.'; if(!data.method.unitName)return 'Unit is required.'; if(data.testType){ if(!data.testType.testCode)return 'Test Code is required.'; if(state.testTypes.some((t)=>t.testCode===data.testType.testCode))return `Test Code ${data.testType.testCode} already exists.`; } else if(!data.method.testTypeId)return 'Select a Test Code.'; return ''; }
function methodPayload(method,testTypeId){ const existing=state.methods.find((row)=>row.id===state.editingId); const code=state.testTypes.find((row)=>row.id===testTypeId)?.testCode||''; return { test_type_id:testTypeId,item_key:existing?.itemKey||normalizeKey(`${code}_${method.method}_${method.description}`)||uid('METHOD').toUpperCase(),price_section:method.priceSection,category:method.category,method:method.method,description:method.description,unit_name:method.unitName,sort_order:method.sortOrder,is_active:method.isActive!==false,notes:method.notes }; }
async function saveMethod(){ if(state.saving)return; const data=readMethodForm(); const error=validateForm(data); if(error){alert(error);return;} state.saving=true; showStatus('saving','SAVING...'); try { if(isRemote()){ if(data.testType){ const existing=state.methods.find((m)=>m.id===state.editingId); await window.appAuth.requestJson('/rest/v1/rpc/admin_create_billing_method_with_test_type',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({method_record:{id:existing?.id||'',item_key:existing?.itemKey||normalizeKey(`${data.testType.testCode}_${data.method.method}_${data.method.description}`),price_section:data.method.priceSection,category:data.method.category,method:data.method.method,description:data.method.description,unit_name:data.method.unitName,sort_order:data.method.sortOrder,notes:data.method.notes},test_type_record:{test_code:data.testType.testCode,display_label:data.testType.displayLabel||data.testType.testCode,short_label:data.testType.shortLabel||data.testType.displayLabel||data.testType.testCode,minutes:data.testType.minutes,count_mode:data.testType.countMode,matrix_type:data.testType.matrixType,group_key:data.testType.groupKey,group_rank:data.testType.groupRank,aliases:data.testType.aliases,lab_wip_enabled:data.testType.labWipEnabled}})}); } else { const existing=state.methods.find((m)=>m.id===state.editingId); const payload=methodPayload(data.method,data.method.testTypeId); await window.appAuth.requestJson(`/rest/v1/billing_price_items${existing?`?id=eq.${encodeURIComponent(existing.id)}`:''}`,{method:existing?'PATCH':'POST',headers:{'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify(payload)}); } } else { await saveLocalMethod(data); } await loadData(); closeMethodModal(); showStatus('saved','SAVED'); } catch(err){ console.error(err); showStatus('error','SAVE FAILED'); alert(err.message||'Unable to save method.'); } finally { state.saving=false; } }
async function saveLocalMethod(data){ const storage=localStorageAdapter(); const fieldResult=await storage.get(FIELD_STORAGE_KEY); const field=fieldResult?.value?JSON.parse(fieldResult.value):{}; field.priceItems=Array.isArray(field.priceItems)?field.priceItems:[]; field.testTypes=Array.isArray(field.testTypes)&&field.testTypes.length?field.testTypes:state.testTypes.map((type)=>({...type,key:type.testCode,label:type.displayLabel,shortLabel:type.shortLabel})); let typeId=data.method.testTypeId; if(data.testType){ typeId=uid('testtype'); field.testTypes.push({...data.testType,id:typeId,key:data.testType.testCode,label:data.testType.displayLabel||data.testType.testCode,shortLabel:data.testType.shortLabel||data.testType.displayLabel||data.testType.testCode,isActive:true,sortOrder:field.testTypes.length}); await storage.set(TEST_STORAGE_KEY,JSON.stringify(field.testTypes)); } const index=field.priceItems.findIndex((m)=>m.id===state.editingId); const prior=index>=0?field.priceItems[index]:null; const record={...prior,...data.method,id:prior?.id||uid('priceitem'),testTypeId:typeId,itemKey:prior?.itemKey||normalizeKey(`${data.testType?.testCode||''}_${data.method.method}_${data.method.description}`)}; if(index>=0)field.priceItems[index]=record;else field.priceItems.push(record); await storage.set(FIELD_STORAGE_KEY,JSON.stringify(field)); }
async function toggleMethodArchive(id){ const method=state.methods.find((row)=>row.id===id); if(!method)return; const nextActive=method.isActive===false; try { if(isRemote())await window.appAuth.requestJson(`/rest/v1/billing_price_items?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_active:nextActive})}); else { const storage=localStorageAdapter(); const result=await storage.get(FIELD_STORAGE_KEY); const field=result?.value?JSON.parse(result.value):{}; const row=(field.priceItems||[]).find((m)=>m.id===id); if(row)row.isActive=nextActive; await storage.set(FIELD_STORAGE_KEY,JSON.stringify(field)); } await loadData(); } catch(err){alert(err.message||'Unable to update method.');} }
function showStatus(kind,text){ const node=document.getElementById('save-indicator'); node.style.visibility='visible'; node.className=`save-indicator ${kind}`; node.textContent=text; setTimeout(()=>{node.style.visibility='hidden';},2200); }
(async function init(){ await (window.authReadyPromise||Promise.resolve()); try{await loadData();}catch(err){console.error(err);document.getElementById('last-update').textContent='Unable to load methods';} })();
