const FIELD_STORAGE_KEY='field-ops-dashboard-data';
const TEST_STORAGE_KEY='lab-wip-test-definitions';
const state={tab:'tests',search:'',status:'active',methods:[],tests:[],aliases:[],services:[],priceItems:[],legacy:[],billingPrices:[],setups:[],editingId:'',modalKind:'',saving:false};
const esc=(value)=>String(value??'').replace(/[&<>"']/g,(ch)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const uid=(prefix)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const normalizeCode=(value)=>String(value||'').trim().toUpperCase().replace(/\s+/g,'_').replace(/[^A-Z0-9_-]/g,'');
const isRemote=()=>window.appAuth?.getMode?.()==='remote';
const storageAdapter=()=>window.storage||{get:async(key)=>({value:localStorage.getItem(key)}),set:async(key,value)=>localStorage.setItem(key,value)};
const methodLabel=(method)=>method?`${method.designation}${method.revision?` (${method.revision})`:''}`:'No method';
const canManageCatalog=()=>!isRemote()||window.appAuth?.isAdmin?.()===true;

function normalizeMethod(row,remote=false){return {id:String(row?.id||uid('method')),organization:String((remote?row?.organization:row?.organization)||''),designation:String((remote?row?.standard_designation:(row?.designation||row?.standardDesignation))||''),title:String((remote?row?.method_title:(row?.title||row?.methodTitle))||''),revision:String((remote?row?.revision:row?.revision)||''),effectiveDate:String((remote?row?.effective_date:(row?.effectiveDate))||''),documentReference:String((remote?row?.document_reference:(row?.documentReference))||''),notes:String(row?.notes||''),isActive:(remote?row?.is_active:row?.isActive)!==false};}
function normalizeTest(row,remote=false){return {id:String(row?.id||row?.key||uid('test')),testCode:normalizeCode(remote?row?.test_code:(row?.testCode||row?.key)),testName:String((remote?row?.test_name:(row?.testName||row?.displayLabel||row?.label))||''),matrixType:String((remote?row?.matrix_type:row?.matrixType)||'Unspecified'),methodId:String((remote?row?.method_id:row?.methodId)||''),isActive:(remote?row?.is_active:row?.isActive)!==false};}
function normalizeAlias(row,remote=false){return {id:String(row?.id||uid('alias')),testTypeId:String((remote?row?.test_type_id:row?.testTypeId)||''),aliasCode:String((remote?row?.alias_code:row?.aliasCode)||''),aliasKind:String((remote?row?.alias_kind:row?.aliasKind)||'manual')};}
function normalizeService(row,remote=false){return {id:String(row?.id||uid('service')),serviceCode:normalizeCode(remote?row?.service_code:row?.serviceCode),serviceName:String((remote?row?.service_name:row?.serviceName)||''),category:String((remote?row?.category:row?.category)||'Services'),unitName:String((remote?row?.unit_name:row?.unitName)||'Each'),notes:String(row?.notes||''),isActive:(remote?row?.is_active:row?.isActive)!==false};}
function normalizePriceItem(row,remote=false){return {id:String(row?.id||uid('price')),testTypeId:String((remote?row?.test_type_id:row?.testTypeId)||''),serviceId:String((remote?row?.service_id:row?.serviceId)||''),itemKey:String((remote?row?.item_key:row?.itemKey)||''),itemKind:String((remote?row?.item_kind:row?.itemKind)||(row?.testTypeId?'test':'legacy')),legacyStatus:String((remote?row?.legacy_status:row?.legacyStatus)||'needs_mapping'),method:String(row?.method||''),description:String(row?.description||''),category:String(row?.category||''),unitName:String((remote?row?.unit_name:row?.unitName)||'Per Sample'),notes:String(row?.notes||''),isActive:(remote?row?.is_active:row?.isActive)!==false};}

function migrateLocalCatalog(field,legacyDefs){
  const rawTests=Array.isArray(field.testTypes)&&field.testTypes.length?field.testTypes:(Array.isArray(legacyDefs)?legacyDefs:[]);
  const tests=rawTests.map((row)=>normalizeTest(row));
  const methodMap=new Map((field.labMethods||[]).map((row)=>{const method=normalizeMethod(row);return [`${method.designation.toLowerCase()}::${method.revision.toLowerCase()}`,method];}));
  (field.priceItems||[]).forEach((item)=>{const designation=String(item.method||'').trim();const key=`${designation.toLowerCase()}::`;if(designation&&!methodMap.has(key))methodMap.set(key,normalizeMethod({id:uid('method'),designation,notes:'Imported from the legacy billing catalog.'}));});
  const methods=[...methodMap.values()];
  const methodByDesignation=new Map(methods.filter((m)=>!m.revision).map((m)=>[m.designation.toLowerCase(),m]));
  tests.forEach((test)=>{if(test.methodId)return;const linked=(field.priceItems||[]).filter((item)=>String(item.testTypeId||'')===test.id&&String(item.method||'').trim());const names=[...new Set(linked.map((item)=>String(item.method).trim().toLowerCase()))];if(names.length===1)test.methodId=methodByDesignation.get(names[0])?.id||'';});
  let aliases=(field.labTestTypeAliases||[]).map((row)=>normalizeAlias(row));
  if(!aliases.length){rawTests.forEach((row)=>{const test=tests.find((item)=>item.id===String(row.id||row.key));const values=[test?.testCode,...(Array.isArray(row.aliases)?row.aliases:[])];[...new Set(values.filter(Boolean))].forEach((alias)=>aliases.push(normalizeAlias({testTypeId:test?.id,aliasCode:alias,aliasKind:normalizeCode(alias)===test?.testCode?'canonical':'manual'})));});}
  const services=(field.billingServices||[]).map((row)=>normalizeService(row));
  const priceItems=(field.priceItems||[]).map((row)=>normalizePriceItem(row));
  let setups=Array.isArray(field.labTestSetups)?field.labTestSetups:[];
  if(!setups.length){
    const sites=Array.isArray(field.splSites)&&field.splSites.length?field.splSites:[{id:'pittsburgh',siteCode:'PITTSBURGH'}];
    const pittsburgh=sites.find((site)=>String(site.siteCode||site.site_code)==='PITTSBURGH')||sites[0];
    setups=tests.map((test,index)=>{const old=rawTests.find((row)=>String(row.id||row.key)===test.id)||legacyDefs.find((row)=>String(row.id||row.key)===test.id)||{};return {id:`migration-${test.id||index}`,testTypeId:test.id,splSiteId:String(pittsburgh.id),setupKind:'migration_pending',instrumentId:'',estimatedMinutes:Number(old.minutes||0),workloadCounting:old.countMode==='perRow'?'per_import_row':'per_sample',workloadBundle:old.groupKey||'',bundlePriority:Number(old.groupRank||0),isMigrationPlaceholder:true,isActive:old.labWipEnabled!==false&&test.isActive,notes:'Migrated setup. Assign an instrument or choose No instrument required.'};});
  }
  tests.forEach((test)=>{if(!priceItems.some((item)=>item.itemKind==='test'&&item.testTypeId===test.id))priceItems.push(normalizePriceItem({id:`price-test-${test.id}`,itemKey:`TEST_${test.id}`,itemKind:'test',legacyStatus:'resolved',testTypeId:test.id,isActive:test.isActive}));});
  services.forEach((service)=>{if(!priceItems.some((item)=>item.itemKind==='service'&&item.serviceId===service.id))priceItems.push(normalizePriceItem({id:`price-service-${service.id}`,itemKey:`SERVICE_${service.id}`,itemKind:'service',legacyStatus:'resolved',serviceId:service.id,unitName:service.unitName,isActive:service.isActive}));});
  priceItems.forEach((item)=>{if(!['test','service'].includes(item.itemKind)){item.itemKind='legacy';item.legacyStatus=item.legacyStatus==='resolved'?'resolved':'needs_mapping';}});
  return {methods,tests,aliases,services,priceItems,setups,billingPrices:Array.isArray(field.billingProfilePrices)?field.billingProfilePrices:[]};
}

async function loadData(){
  if(isRemote()){
    const [methods,tests,aliases,services,priceItems,billingPrices]=await Promise.all([
      window.appAuth.requestJson('/rest/v1/lab_methods?select=*&order=standard_designation.asc,revision.asc'),
      window.appAuth.requestJson('/rest/v1/lab_test_types?select=*&order=test_code.asc'),
      window.appAuth.requestJson('/rest/v1/lab_test_type_aliases?select=*&order=alias_code.asc'),
      window.appAuth.requestJson('/rest/v1/billing_services?select=*&order=service_code.asc'),
      window.appAuth.requestJson('/rest/v1/billing_price_items?select=*&order=description.asc'),
      window.appAuth.requestJson('/rest/v1/field_billing_profile_prices?select=*')
    ]);
    state.methods=(methods||[]).map((row)=>normalizeMethod(row,true));state.tests=(tests||[]).map((row)=>normalizeTest(row,true));state.aliases=(aliases||[]).map((row)=>normalizeAlias(row,true));state.services=(services||[]).map((row)=>normalizeService(row,true));state.priceItems=(priceItems||[]).map((row)=>normalizePriceItem(row,true));state.billingPrices=billingPrices||[];
  }else{
    const store=storageAdapter();const [fieldResult,testResult]=await Promise.all([store.get(FIELD_STORAGE_KEY),store.get(TEST_STORAGE_KEY)]);const field=fieldResult?.value?JSON.parse(fieldResult.value):{};const defs=testResult?.value?JSON.parse(testResult.value):[];Object.assign(state,migrateLocalCatalog(field,defs));
  }
  state.legacy=state.priceItems.filter((item)=>item.itemKind==='legacy'&&item.legacyStatus!=='resolved');render();
}

async function persistLocal(){
  const store=storageAdapter();const result=await store.get(FIELD_STORAGE_KEY);const field=result?.value?JSON.parse(result.value):{};
  field.labMethods=state.methods;field.testTypes=state.tests;field.labTestTypeAliases=state.aliases;field.billingServices=state.services;field.priceItems=state.priceItems;field.billingProfilePrices=state.billingPrices;field.labTestSetups=state.setups;
  await store.set(FIELD_STORAGE_KEY,JSON.stringify(field));
}

function selectCatalogTab(tab){state.tab=tab;state.search='';document.getElementById('catalog-search').value='';render();}
function setCatalogSearch(value){state.search=String(value||'').trim().toLowerCase();renderTable();}
function setCatalogStatus(value){state.status=value;renderTable();}
function statusMatch(row){return state.status==='all'||(state.status==='active'&&row.isActive!==false)||(state.status==='archived'&&row.isActive===false);}
function queryMatch(values){return !state.search||values.some((value)=>String(value||'').toLowerCase().includes(state.search));}
function aliasesFor(testId){return state.aliases.filter((alias)=>alias.testTypeId===testId);}
function methodFor(test){return state.methods.find((method)=>method.id===test.methodId)||null;}
function priceUsage(itemId){return state.billingPrices.filter((row)=>String(row.price_item_id||row.priceItemId||'')===itemId).length;}
function legacyUsage(item){return priceUsage(item.id);}

function render(){
  document.body.classList.toggle('catalog-read-only',!canManageCatalog());
  document.querySelectorAll('.catalog-tab').forEach((node)=>node.classList.toggle('active',node.dataset.tab===state.tab));
  document.getElementById('count-tests').textContent=state.tests.length;document.getElementById('count-methods').textContent=state.methods.length;document.getElementById('count-services').textContent=state.services.length;document.getElementById('count-legacy').textContent=state.legacy.length;
  const meta={tests:['Test Types','+ Add Test Type','Unique Test Codes with one Test Name, editable Matrix, and an optional reusable Method. Aliases are retained for imports and history.'],methods:['Methods','+ Add Method','Methods are reusable standards. A separate record represents each revision.'],services:['Billing Services','+ Add Service','Non-test billable items such as mileage, labor, and disposal.'],legacy:['Legacy Items','Resolve Legacy Items','Existing billing rows remain here until mapped to a Test Type or converted to a Service. Rates are preserved.']}[state.tab];
  document.getElementById('catalog-heading').textContent=meta[0];document.getElementById('catalog-add-button').textContent=meta[1];document.getElementById('catalog-add-button').style.display=state.tab==='legacy'||!canManageCatalog()?'none':'';document.getElementById('catalog-help').textContent=`${meta[2]}${canManageCatalog()?'':' Read-only access.'}`;document.getElementById('catalog-status').style.display=state.tab==='legacy'?'none':'';renderTable();
}

function renderTable(){
  let head='',rows=[];
  if(state.tab==='tests'){
    head='<tr><th>Test Code</th><th>Test Name</th><th>Matrix</th><th>Method / Standard</th><th>Aliases</th><th>Status</th><th></th></tr>';
    rows=state.tests.filter(statusMatch).filter((test)=>queryMatch([test.testCode,test.testName,test.matrixType,methodLabel(methodFor(test)),...aliasesFor(test.id).map((a)=>a.aliasCode)])).sort((a,b)=>a.testCode.localeCompare(b.testCode)).map((test)=>`<tr><td class="primary">${esc(test.testCode)}</td><td>${esc(test.testName)}</td><td>${esc(test.matrixType||'Unspecified')}</td><td>${esc(methodLabel(methodFor(test)))}</td><td>${esc(aliasesFor(test.id).filter((a)=>a.aliasKind!=='canonical').map((a)=>a.aliasCode).join(', ')||'—')}</td><td><span class="status-pill ${test.isActive?'active':'archived'}">${test.isActive?'Active':'Archived'}</span></td><td><div class="catalog-actions"><button class="sec-btn" onclick="openCatalogModal('${esc(test.id)}')">Edit</button><button class="sec-btn" onclick="toggleArchive('tests','${esc(test.id)}')">${test.isActive?'Archive':'Restore'}</button></div></td></tr>`);
  }else if(state.tab==='methods'){
    head='<tr><th>Organization</th><th>Method / Standard</th><th>Title</th><th>Revision</th><th>Effective</th><th>Linked Tests</th><th>Status</th><th></th></tr>';
    rows=state.methods.filter(statusMatch).filter((method)=>queryMatch([method.organization,method.designation,method.title,method.revision,method.documentReference])).sort((a,b)=>a.designation.localeCompare(b.designation)||a.revision.localeCompare(b.revision)).map((method)=>`<tr><td>${esc(method.organization||'—')}</td><td class="primary">${esc(method.designation)}</td><td>${esc(method.title||'—')}</td><td>${esc(method.revision||'Current / unspecified')}</td><td>${esc(method.effectiveDate||'—')}</td><td>${state.tests.filter((test)=>test.methodId===method.id).length}</td><td><span class="status-pill ${method.isActive?'active':'archived'}">${method.isActive?'Active':'Archived'}</span></td><td><div class="catalog-actions"><button class="sec-btn" onclick="openCatalogModal('${esc(method.id)}')">Edit</button><button class="sec-btn" onclick="toggleArchive('methods','${esc(method.id)}')">${method.isActive?'Archive':'Restore'}</button></div></td></tr>`);
  }else if(state.tab==='services'){
    head='<tr><th>Service Code</th><th>Service Name</th><th>Category</th><th>Unit</th><th>Status</th><th></th></tr>';
    rows=state.services.filter(statusMatch).filter((service)=>queryMatch([service.serviceCode,service.serviceName,service.category,service.unitName])).sort((a,b)=>a.serviceCode.localeCompare(b.serviceCode)).map((service)=>`<tr><td class="primary">${esc(service.serviceCode)}</td><td>${esc(service.serviceName)}</td><td>${esc(service.category)}</td><td>${esc(service.unitName)}</td><td><span class="status-pill ${service.isActive?'active':'archived'}">${service.isActive?'Active':'Archived'}</span></td><td><div class="catalog-actions"><button class="sec-btn" onclick="openCatalogModal('${esc(service.id)}')">Edit</button><button class="sec-btn" onclick="toggleArchive('services','${esc(service.id)}')">${service.isActive?'Archive':'Restore'}</button></div></td></tr>`);
  }else{
    head='<tr><th>Legacy Key</th><th>Method</th><th>Description</th><th>Category</th><th>Unit</th><th>Client Rates</th><th>Status</th><th></th></tr>';
    rows=state.legacy.filter((item)=>queryMatch([item.itemKey,item.method,item.description,item.category,item.unitName])).map((item)=>`<tr><td class="primary">${esc(item.itemKey)}</td><td>${esc(item.method||'—')}</td><td>${esc(item.description||'—')}</td><td>${esc(item.category||'—')}</td><td>${esc(item.unitName)}</td><td>${legacyUsage(item)}</td><td><span class="status-pill ${item.legacyStatus==='conflict'?'danger':'warn'}">${esc(item.legacyStatus==='conflict'?'Conflict':'Needs mapping')}</span></td><td><button class="sec-btn" onclick="openLegacyModal('${esc(item.id)}')">Resolve</button></td></tr>`);
  }
  document.getElementById('catalog-thead').innerHTML=head;document.getElementById('catalog-tbody').innerHTML=rows.length?rows.join(''):`<tr><td class="empty-cell" colspan="8">No ${esc(state.tab==='legacy'?'legacy items':'catalog records')} match these filters.</td></tr>`;document.getElementById('last-update').textContent=`${rows.length} shown | ${isRemote()?'Remote':'Local'} | ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`;
}

function methodOptions(selected=''){return ['<option value="">No method</option>',...state.methods.filter((m)=>m.isActive||m.id===selected).sort((a,b)=>a.designation.localeCompare(b.designation)||a.revision.localeCompare(b.revision)).map((m)=>`<option value="${esc(m.id)}" ${m.id===selected?'selected':''}>${esc(methodLabel(m))}${m.isActive?'':' [Archived]'}</option>`)].join('');}
function openCatalogModal(id=''){
  if(!canManageCatalog())return;
  state.modalKind=state.tab;state.editingId=id;let title='',body='';
  if(state.tab==='tests'){const row=state.tests.find((item)=>item.id===id)||{testCode:'',testName:'',matrixType:'',methodId:'',isActive:true};title=id?'Edit Test Type':'Add Test Type';const aliases=aliasesFor(id).filter((a)=>a.aliasKind==='manual').map((a)=>a.aliasCode).join(', ');const historical=aliasesFor(id).filter((a)=>a.aliasKind==='historical').map((a)=>a.aliasCode).join(', ');body=`<div class="form-grid"><div class="form-group"><label class="form-label">Test Code *</label><input class="form-input" id="cat-test-code" value="${esc(row.testCode)}" placeholder="GC-C6GAS"></div><div class="form-group"><label class="form-label">Test Name *</label><input class="form-input" id="cat-test-name" value="${esc(row.testName)}" placeholder="Natural Gas Composition"></div><div class="form-group"><label class="form-label">Matrix</label><select class="form-input" id="cat-matrix"><option value="">Unspecified</option>${['Gas','Liquid','Calculated'].map((v)=>`<option ${row.matrixType===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="form-group"><label class="form-label">Method / Standard</label><select class="form-input" id="cat-method-id">${methodOptions(row.methodId)}</select></div><div class="form-group full"><label class="form-label">Import aliases</label><input class="form-input" id="cat-aliases" value="${esc(aliases)}" placeholder="Comma separated legacy or alternate codes"><div class="aliases-note">The canonical Test Code is always recognized.${historical?` Historical aliases retained automatically: ${esc(historical)}`:''}</div></div><div class="form-group full"><label class="check-row"><input id="cat-active" type="checkbox" ${row.isActive?'checked':''}> Active Test Type</label></div></div>`;}
  if(state.tab==='methods'){const row=state.methods.find((item)=>item.id===id)||{organization:'',designation:'',title:'',revision:'',effectiveDate:'',documentReference:'',notes:'',isActive:true};title=id?'Edit Method':'Add Method';body=`<div class="form-grid"><div class="form-group"><label class="form-label">Organization</label><input class="form-input" id="cat-organization" value="${esc(row.organization)}" placeholder="ASTM, GPA, SPL"></div><div class="form-group"><label class="form-label">Method / Standard *</label><input class="form-input" id="cat-designation" value="${esc(row.designation)}" placeholder="ASTM D6377"></div><div class="form-group full"><label class="form-label">Title / Description</label><input class="form-input" id="cat-title" value="${esc(row.title)}"></div><div class="form-group"><label class="form-label">Revision</label><input class="form-input" id="cat-revision" value="${esc(row.revision)}" placeholder="2024"></div><div class="form-group"><label class="form-label">Effective Date</label><input class="form-input" id="cat-effective" type="date" value="${esc(row.effectiveDate)}"></div><div class="form-group full"><label class="form-label">Document Reference</label><input class="form-input" id="cat-document" value="${esc(row.documentReference)}" placeholder="URL, document number, or controlled copy reference"></div><div class="form-group full"><label class="form-label">Notes</label><textarea class="form-input" id="cat-notes">${esc(row.notes)}</textarea></div><div class="form-group full"><label class="check-row"><input id="cat-active" type="checkbox" ${row.isActive?'checked':''}> Active Method</label></div></div>`;}
  if(state.tab==='services'){const row=state.services.find((item)=>item.id===id)||{serviceCode:'',serviceName:'',category:'Services',unitName:'Each',notes:'',isActive:true};title=id?'Edit Billing Service':'Add Billing Service';body=`<div class="form-grid"><div class="form-group"><label class="form-label">Service Code *</label><input class="form-input" id="cat-service-code" value="${esc(row.serviceCode)}" placeholder="VEHICLE_MILEAGE"></div><div class="form-group"><label class="form-label">Service Name *</label><input class="form-input" id="cat-service-name" value="${esc(row.serviceName)}"></div><div class="form-group"><label class="form-label">Category</label><input class="form-input" id="cat-category" value="${esc(row.category)}"></div><div class="form-group"><label class="form-label">Unit *</label><input class="form-input" id="cat-unit" value="${esc(row.unitName)}" placeholder="Per Mile"></div><div class="form-group full"><label class="form-label">Notes</label><textarea class="form-input" id="cat-notes">${esc(row.notes)}</textarea></div><div class="form-group full"><label class="check-row"><input id="cat-active" type="checkbox" ${row.isActive?'checked':''}> Active Billing Service</label></div></div>`;}
  document.getElementById('catalog-modal-title').textContent=title;document.getElementById('catalog-modal-body').innerHTML=body;document.getElementById('catalog-modal-save').textContent='Save';document.getElementById('catalog-modal-overlay').classList.add('open');
}
function openLegacyModal(id){const item=state.legacy.find((row)=>row.id===id);if(!item)return;state.modalKind='legacy';state.editingId=id;document.getElementById('catalog-modal-title').textContent='Resolve Legacy Billing Item';document.getElementById('catalog-modal-body').innerHTML=`<div class="form-grid"><div class="form-group full"><div class="primary">${esc(item.method||'No method')} | ${esc(item.description||item.itemKey)}</div><div class="secondary">${legacyUsage(item)} retained client rate record(s)</div></div><div class="form-group"><label class="form-label">Resolve As</label><select class="form-input" id="legacy-kind" onchange="toggleLegacyTarget(this.value)"><option value="test">Map to Test Type</option><option value="service">Convert to Billing Service</option></select></div><div class="form-group"><label class="form-label">Rate Conflict Action</label><select class="form-input" id="legacy-conflict"><option value="error">Stop and report conflicts</option><option value="keep_target">Keep existing catalog rate</option><option value="replace_target">Replace with legacy rate</option></select></div><div class="form-grid full legacy-choice open" id="legacy-test-fields"><div class="form-group full"><label class="form-label">Test Type</label><select class="form-input" id="legacy-test-id"><option value="">Select Test Type...</option>${state.tests.filter((t)=>t.isActive).sort((a,b)=>a.testCode.localeCompare(b.testCode)).map((t)=>`<option value="${esc(t.id)}">${esc(t.testCode)} | ${esc(t.testName)}</option>`).join('')}</select></div></div><div class="form-grid full legacy-choice" id="legacy-service-fields"><div class="form-group"><label class="form-label">Service Code</label><input class="form-input" id="legacy-service-code" value="${esc(normalizeCode(item.itemKey))}"></div><div class="form-group"><label class="form-label">Service Name</label><input class="form-input" id="legacy-service-name" value="${esc(item.description)}"></div><div class="form-group"><label class="form-label">Category</label><input class="form-input" id="legacy-service-category" value="${esc(item.category||'Services')}"></div><div class="form-group"><label class="form-label">Unit</label><input class="form-input" id="legacy-service-unit" value="${esc(item.unitName||'Each')}"></div></div></div>`;document.getElementById('catalog-modal-save').textContent='Resolve Item';document.getElementById('catalog-modal-overlay').classList.add('open');}
function toggleLegacyTarget(kind){document.getElementById('legacy-test-fields').classList.toggle('open',kind==='test');document.getElementById('legacy-service-fields').classList.toggle('open',kind==='service');}
function closeCatalogModal(){state.editingId='';state.modalKind='';document.getElementById('catalog-modal-overlay').classList.remove('open');}

async function saveCatalogModal(){if(state.saving)return;if(state.modalKind==='legacy')return resolveLegacyItem();let record,payload,url,method;
  if(state.modalKind==='tests'){record={id:state.editingId,testCode:normalizeCode(document.getElementById('cat-test-code').value),testName:document.getElementById('cat-test-name').value.trim(),matrixType:document.getElementById('cat-matrix').value||'Unspecified',methodId:document.getElementById('cat-method-id').value,isActive:document.getElementById('cat-active').checked,aliases:document.getElementById('cat-aliases').value.split(',').map(normalizeCode).filter(Boolean)};if(!record.testCode||!record.testName)return alert('Test Code and Test Name are required.');if(state.tests.some((t)=>t.id!==record.id&&t.testCode===record.testCode))return alert('That Test Code already exists.');}
  if(state.modalKind==='methods'){record={id:state.editingId,organization:document.getElementById('cat-organization').value.trim(),designation:document.getElementById('cat-designation').value.trim(),title:document.getElementById('cat-title').value.trim(),revision:document.getElementById('cat-revision').value.trim(),effectiveDate:document.getElementById('cat-effective').value,documentReference:document.getElementById('cat-document').value.trim(),notes:document.getElementById('cat-notes').value.trim(),isActive:document.getElementById('cat-active').checked};if(!record.designation)return alert('Method / Standard is required.');if(state.methods.some((m)=>m.id!==record.id&&m.designation.toLowerCase()===record.designation.toLowerCase()&&m.revision.toLowerCase()===record.revision.toLowerCase()))return alert('That Method revision already exists.');}
  if(state.modalKind==='services'){record={id:state.editingId,serviceCode:normalizeCode(document.getElementById('cat-service-code').value),serviceName:document.getElementById('cat-service-name').value.trim(),category:document.getElementById('cat-category').value.trim()||'Services',unitName:document.getElementById('cat-unit').value.trim(),notes:document.getElementById('cat-notes').value.trim(),isActive:document.getElementById('cat-active').checked};if(!record.serviceCode||!record.serviceName||!record.unitName)return alert('Service Code, Service Name, and Unit are required.');if(state.services.some((s)=>s.id!==record.id&&s.serviceCode===record.serviceCode))return alert('That Service Code already exists.');}
  state.saving=true;showStatus('saving','SAVING...');try{
    if(isRemote()){
      if(state.modalKind==='tests')await window.appAuth.requestJson('/rest/v1/rpc/admin_save_test_type',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({test_record:{id:record.id,test_code:record.testCode,test_name:record.testName,matrix_type:record.matrixType,method_id:record.methodId,is_active:record.isActive},alias_values:record.aliases})});
      if(state.modalKind==='methods'){payload={organization:record.organization,standard_designation:record.designation,method_title:record.title,revision:record.revision,effective_date:record.effectiveDate||null,document_reference:record.documentReference,notes:record.notes,is_active:record.isActive};url=`/rest/v1/lab_methods${record.id?`?id=eq.${encodeURIComponent(record.id)}`:''}`;method=record.id?'PATCH':'POST';await window.appAuth.requestJson(url,{method,headers:{'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify(payload)});}
      if(state.modalKind==='services'){payload={service_code:record.serviceCode,service_name:record.serviceName,category:record.category,unit_name:record.unitName,notes:record.notes,is_active:record.isActive};url=`/rest/v1/billing_services${record.id?`?id=eq.${encodeURIComponent(record.id)}`:''}`;method=record.id?'PATCH':'POST';await window.appAuth.requestJson(url,{method,headers:{'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify(payload)});}
    }else saveLocalCatalogRecord(state.modalKind,record);
    if(!isRemote())await persistLocal();await loadData();closeCatalogModal();showStatus('saved','SAVED');
  }catch(error){console.error(error);showStatus('error','SAVE FAILED');alert(error.message||'Unable to save catalog record.');}finally{state.saving=false;}
}

function saveLocalCatalogRecord(kind,record){
  if(kind==='tests'){const prior=state.tests.find((t)=>t.id===record.id);const id=prior?.id||uid('test');if(prior&&prior.testCode!==record.testCode&&!state.aliases.some((a)=>a.testTypeId===id&&a.aliasCode.toLowerCase()===prior.testCode.toLowerCase()))state.aliases.push(normalizeAlias({testTypeId:id,aliasCode:prior.testCode,aliasKind:'historical'}));const next=normalizeTest({...record,id});const index=state.tests.findIndex((t)=>t.id===id);if(index>=0)state.tests[index]=next;else state.tests.push(next);state.aliases=state.aliases.filter((a)=>a.testTypeId!==id||a.aliasKind!=='manual');record.aliases.forEach((alias)=>{const collision=state.aliases.find((a)=>a.aliasCode.toLowerCase()===alias.toLowerCase()&&a.testTypeId!==id);if(collision)throw new Error(`Alias ${alias} is already assigned to another Test Code.`);state.aliases.push(normalizeAlias({testTypeId:id,aliasCode:alias,aliasKind:'manual'}));});if(!state.aliases.some((a)=>a.testTypeId===id&&a.aliasKind==='canonical'))state.aliases.push(normalizeAlias({testTypeId:id,aliasCode:next.testCode,aliasKind:'canonical'}));if(!state.priceItems.some((p)=>p.itemKind==='test'&&p.testTypeId===id))state.priceItems.push(normalizePriceItem({id:`price-test-${id}`,itemKey:`TEST_${id}`,itemKind:'test',legacyStatus:'resolved',testTypeId:id,isActive:next.isActive}));}
  if(kind==='methods'){const next=normalizeMethod({...record,id:record.id||uid('method')});const index=state.methods.findIndex((m)=>m.id===next.id);if(index>=0)state.methods[index]=next;else state.methods.push(next);}
  if(kind==='services'){const next=normalizeService({...record,id:record.id||uid('service')});const index=state.services.findIndex((s)=>s.id===next.id);if(index>=0)state.services[index]=next;else state.services.push(next);let price=state.priceItems.find((p)=>p.itemKind==='service'&&p.serviceId===next.id);if(price){price.isActive=next.isActive;price.unitName=next.unitName;}else state.priceItems.push(normalizePriceItem({id:`price-service-${next.id}`,itemKey:`SERVICE_${next.id}`,itemKind:'service',legacyStatus:'resolved',serviceId:next.id,unitName:next.unitName,isActive:next.isActive}));}
}

async function toggleArchive(kind,id){if(!canManageCatalog())return;const list=kind==='tests'?state.tests:kind==='methods'?state.methods:state.services;const row=list.find((item)=>item.id===id);if(!row)return;try{if(isRemote()){const table=kind==='tests'?'lab_test_types':kind==='methods'?'lab_methods':'billing_services';await window.appAuth.requestJson(`/rest/v1/${table}?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_active:!row.isActive})});}else{row.isActive=!row.isActive;if(kind==='tests')state.priceItems.filter((p)=>p.itemKind==='test'&&p.testTypeId===id).forEach((p)=>p.isActive=row.isActive);if(kind==='services')state.priceItems.filter((p)=>p.itemKind==='service'&&p.serviceId===id).forEach((p)=>p.isActive=row.isActive);await persistLocal();}await loadData();}catch(error){alert(error.message||'Unable to update catalog status.');}}

async function resolveLegacyItem(){
  const item=state.legacy.find((row)=>row.id===state.editingId);if(!item)return;
  const kind=document.getElementById('legacy-kind').value;
  const action=document.getElementById('legacy-conflict').value;
  const testId=document.getElementById('legacy-test-id').value;
  const serviceRecord={service_code:normalizeCode(document.getElementById('legacy-service-code').value),service_name:document.getElementById('legacy-service-name').value.trim(),category:document.getElementById('legacy-service-category').value.trim(),unit_name:document.getElementById('legacy-service-unit').value.trim()};
  if(kind==='test'&&!testId)return alert('Select a Test Type.');
  if(kind==='service'&&(!serviceRecord.service_code||!serviceRecord.service_name||!serviceRecord.unit_name))return alert('Complete the Billing Service fields.');
  state.saving=true;showStatus('saving','RESOLVING...');
  try{
    if(isRemote()){
      const result=await window.appAuth.requestJson('/rest/v1/rpc/admin_resolve_legacy_billing_item',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({legacy_item_id:item.id,target_kind:kind,target_id:kind==='test'?testId:null,conflict_action:action,service_record:serviceRecord})});
      if(result?.status==='conflict')throw new Error(`${result.conflicts} client/year rate conflict${result.conflicts===1?'':'s'} found. Choose which saved rate to keep.`);
    }else{resolveLocalLegacy(item,kind,testId,serviceRecord,action);await persistLocal();}
    await loadData();closeCatalogModal();showStatus('saved','RESOLVED');
  }catch(error){console.error(error);item.legacyStatus='conflict';if(!isRemote())await persistLocal();showStatus('error','RESOLVE FAILED');alert(error.message||'Unable to resolve legacy item.');render();}
  finally{state.saving=false;}
}
function resolveLocalLegacy(item,kind,testId,serviceRecord,action){let target;if(kind==='test')target=state.priceItems.find((p)=>p.itemKind==='test'&&p.testTypeId===testId);else{const service=normalizeService({...serviceRecord,id:uid('service'),serviceCode:serviceRecord.service_code,serviceName:serviceRecord.service_name,unitName:serviceRecord.unit_name,isActive:true});state.services.push(service);target=normalizePriceItem({id:`price-service-${service.id}`,itemKey:`SERVICE_${service.id}`,itemKind:'service',legacyStatus:'resolved',serviceId:service.id,unitName:service.unitName,isActive:true});state.priceItems.push(target);}if(!target)throw new Error('Catalog billing entry was not found.');const conflicts=state.billingPrices.filter((legacy)=>String(legacy.priceItemId||legacy.price_item_id)===item.id&&state.billingPrices.some((other)=>String(other.priceItemId||other.price_item_id)===target.id&&String(other.billingProfileId||other.billing_profile_id)===String(legacy.billingProfileId||legacy.billing_profile_id)&&Number(other.effectiveYear||other.effective_year)===Number(legacy.effectiveYear||legacy.effective_year)));if(conflicts.length&&action==='error')throw new Error('Existing client/year rates conflict. Choose a conflict action.');if(action==='keep_target')state.billingPrices=state.billingPrices.filter((row)=>!conflicts.includes(row));if(action==='replace_target'){const keys=new Set(conflicts.map((row)=>`${row.billingProfileId||row.billing_profile_id}::${row.effectiveYear||row.effective_year}`));state.billingPrices=state.billingPrices.filter((row)=>String(row.priceItemId||row.price_item_id)!==target.id||!keys.has(`${row.billingProfileId||row.billing_profile_id}::${row.effectiveYear||row.effective_year}`));}state.billingPrices.forEach((row)=>{if(String(row.priceItemId||row.price_item_id)===item.id){if('priceItemId'in row)row.priceItemId=target.id;else row.price_item_id=target.id;}});item.legacyStatus='resolved';item.isActive=false;}
function showStatus(kind,text){const node=document.getElementById('save-indicator');node.style.visibility='visible';node.className=`save-indicator ${kind}`;node.textContent=text;setTimeout(()=>node.style.visibility='hidden',2200);}
document.getElementById('catalog-modal-overlay').addEventListener('click',(event)=>{if(event.target===event.currentTarget)closeCatalogModal();});
(async function init(){await(window.authReadyPromise||Promise.resolve());try{await loadData();}catch(error){console.error(error);document.getElementById('last-update').textContent='Unable to load catalog';alert(error.message||'Unable to load Test Catalog.');}})();
